-- No-op post-migration vim.pack (2026-05-16).
-- LuaSnip is now installed and built by upstream init.lua via the
-- `PackChanged` build hook (runs `make install_jsregexp` automatically).
-- The previous `branch = 'master'` workaround is no longer needed —
-- vim.pack pins to `vim.version.range '2.*'` and upstream LuaSnip 2.x
-- ships a fixed Makefile in recent releases.
--
-- Safe to delete this file. Kept as a stub during migration so the
-- diff in git history stays comprehensible. Run:
--   git rm lua/custom/plugins/luasnip-override.lua
